### ISSUE TITLE
Timestamp support

### ISSUE THREAD

**Issue by amanfrinati** [govert/SQLiteForExcel#3]
Hi,
i'm working with your .bas with excel. After lots of tries i found that you have not insert a stdcall for bind timestamp, because your stdcall for bind date converts date value in double.
There is a way to solve this issue?
Thank you!

**Comment by govert** [comment]
Hi Alberto,

What exactly do you mean by a Timestamp?
Do you mean a Date value that only has a time portion, or some sequential counter?

Internally, SQLite has no date or time storage format.
Am I missing some SQLite function – maybe you can point me to the right documentation.

-Govert

**Comment by amanfrinati** [comment]
Hi Govert,

with timestamp i mean a date value like "2016/09/21 11:52".
In your Sqlite3Demo, when you call SQLite3BindDate, date bind works because your date data type (on the table created in Sub TestBinding) is REAL. In my case however I am working with a table with date data type timestamp.
Maybe I must not use SQLite3BindDate to bind my date value?

**Comment by govert** [comment]
It would depend on how you store the date in the database.

The SQLite3BindDate assumes it is storing the Julian day format (as described here: https://www.sqlite.org/lang_datefunc.html)

If you’re storing as text or a number with different offset, you need to read it back using the appropriate type.
