### ISSUE TITLE
support for sqlite see (encryption)?

### ISSUE THREAD

**Issue by r2evans** [govert/SQLiteForExcel#6]
Does this support accessing sqlite3 databases encrypted with the [SQLite Encryption Extension (SEE)](https://www.sqlite.org/see/doc/trunk/www/index.wiki)? (Because SEE adds more C functions to the interface, I'm guessing "no" or at least "not yet".)

(This could also be done using [SQLCipher](https://github.com/sqlcipher/sqlcipher), I guess.)

**Comment by govert** [comment]
I haven't added anything specific to this, and don't have access to SEE myself. But following the existing API patterns should be straight forward. Maybe you'd like to try and then create a pull request?
