### ISSUE TITLE
sqlite dot-commands

### ISSUE THREAD

**Issue by marnhaccharles** [govert/SQLiteForExcel#8]
Hi,

Many thanks for this work.
However, is it possible to use dot-commands in vba script code? i.e: .import file.csv

Many thanks

**Comment by govert** [comment]
No, I don't think so - those are part of the SQLite3.exe executable shell.
I guess you could put the SQLite.exe in a known location and the run the program from VBA (search for "run exe with parameters using vba" or something similar)
